# TCL File Generated by Component Editor 11.0sp2
# Wed Sep 07 09:47:44 PDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | vj_avalon_master "vj_avalon_master" v1.0
# | null 2011.09.07.09:47:44
# | 
# | 
# | D:/boards/stratix5/stratix5_pcie/pld/system_max/max5_s5_small_test/vj_avalon_master/vj_avalon_master.vhd
# | 
# |    ./vj_avalon_decode.vhd syn, sim
# |    ./vj_avalon_encode.vhd syn, sim
# |    ./vj_avalon_master.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module vj_avalon_master
# | 
set_module_property NAME vj_avalon_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME vj_avalon_master
set_module_property TOP_LEVEL_HDL_FILE vj_avalon_master.vhd
set_module_property TOP_LEVEL_HDL_MODULE vj_avalon_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file vj_avalon_decode.vhd {SYNTHESIS SIMULATION}
add_file vj_avalon_encode.vhd {SYNTHESIS SIMULATION}
add_file vj_avalon_master.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink_reset
# | 
add_interface clock_sink_reset reset end
set_interface_property clock_sink_reset associatedClock clock_sink
set_interface_property clock_sink_reset synchronousEdges DEASSERT

set_interface_property clock_sink_reset ENABLED true

add_interface_port clock_sink_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_master
# | 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset clock_sink_reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0

set_interface_property avalon_master ENABLED true

add_interface_port avalon_master read_n read_n Output 1
add_interface_port avalon_master write_n write_n Output 1
add_interface_port avalon_master address address Output 32
add_interface_port avalon_master data_out writedata Output 32
add_interface_port avalon_master waitrequest_n waitrequest_n Input 1
add_interface_port avalon_master data_in readdata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk_pls_p
# | 
add_interface clk_pls_p conduit end

set_interface_property clk_pls_p ENABLED true

add_interface_port clk_pls_p clk_pls_p export Input 1
# | 
# +-----------------------------------
