# TCL File Generated by Component Editor 11.0sp2
# Thu Sep 22 15:58:06 PDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | i2c_cont_bridge "i2c_cont_bridge" v1.0
# | null 2011.09.22.15:58:06
# | 
# | 
# | D:/boards/stratix5/testchip_demo_board/pld/TC28nm_clcok_n_download_fref_clk33_fix_restore/i2c_cont_bridge.vhd
# | 
# |    ./i2c_cont_bridge.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module i2c_cont_bridge
# | 
set_module_property NAME i2c_cont_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME i2c_cont_bridge
set_module_property TOP_LEVEL_HDL_FILE i2c_cont_bridge.vhd
set_module_property TOP_LEVEL_HDL_MODULE i2c_cont_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME i2c_cont_bridge
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file i2c_cont_bridge.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point slv
# | 
add_interface slv avalon end
set_interface_property slv addressUnits WORDS
set_interface_property slv associatedClock clock
set_interface_property slv associatedReset reset
set_interface_property slv bitsPerSymbol 8
set_interface_property slv burstOnBurstBoundariesOnly false
set_interface_property slv burstcountUnits WORDS
set_interface_property slv explicitAddressSpan 0
set_interface_property slv holdTime 0
set_interface_property slv linewrapBursts false
set_interface_property slv maximumPendingReadTransactions 0
set_interface_property slv readLatency 0
set_interface_property slv readWaitTime 1
set_interface_property slv setupTime 0
set_interface_property slv timingUnits Cycles
set_interface_property slv writeWaitTime 0

set_interface_property slv ENABLED true

add_interface_port slv slv_address address Input 10
add_interface_port slv slv_read_n read_n Input 1
add_interface_port slv slv_write_n write_n Input 1
add_interface_port slv slv_data_in writedata Input 32
add_interface_port slv slv_waitrequest_n waitrequest_n Output 1
add_interface_port slv slv_data_out readdata Output 32
add_interface_port slv slv_en_n chipselect_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_master
# | 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0

set_interface_property avalon_master ENABLED true

add_interface_port avalon_master mstr_en_n chipselect_n Output 1
add_interface_port avalon_master mstr_address address Output 10
add_interface_port avalon_master mstr_write_n write_n Output 1
add_interface_port avalon_master mstr_read_n read_n Output 1
add_interface_port avalon_master mstr_data_in readdata Input 32
add_interface_port avalon_master mstr_data_out writedata Output 32
add_interface_port avalon_master mstr_waitrequest_n waitrequest_n Input 1
# | 
# +-----------------------------------
